In [18]:
api_key = 'WtCLbSmaluaxeipV1QNS5Tnh4q5Qs5s9I6g2kwf4'
base_url = 'https://developer.nrel.gov'
index_api_url = '/api/solar/open_pv/installs/index'
# rankings_api_url = '/api/solar/open_pv/installs/rankings' # based on county
# summaries_api_url = '/api/solar/open_pv/installs/summaries' # state wide

In [53]:
import requests
import json
import pandas as pd
from datetime import datetime

In [11]:
# payload = {'key1': 'value1', 'key2': 'value2'}
payload = {"api_key": api_key,
           "state": "CO",
           "minsize": 1,
           "maxsize": 1000,
           "pagenum": 1,
           "nppage": 25,
           "sort": "size_kw",
           "order": "DESC"
          }
ret = requests.get(base_url + index_api_url, params=payload)

In [47]:
payload = {"api_key": api_key,
           "state": "CO",
           "nppage": 10000,
           "sort": "date_installed"
          }

In [48]:
# print(json.dumps(ret.json(), indent=2))

In [50]:
ret = requests.get(base_url + index_api_url, params=payload)
md = ret.json()
install_df = pd.DataFrame.from_dict(md["result"])
install_df

,_id,cost,date_installed,size_kw,state,zipcode
0,584b035a2c87395595000002,14000.0,1460246400,3.300,CO,80461
1,55e67d5705a4a4e607000002,NaN,1441065600,10.000,CO,80526
2,55a7d2c705a4a41dc7000006,NaN,1434585600,91.810,CO,80521
3,55a7d2c705a4a41dc7000005,NaN,1433289600,220.210,CO,80525
4,55a7d2c705a4a41dc7000007,NaN,1433203200,98.520,CO,80524
5,55a7d2c705a4a41dc7000004,NaN,1429660800,139.080,CO,80521
6,55a7d2c705a4a41dc7000003,NaN,1426550400,544.730,CO,80521
7,55a7d2c705a4a41dc7000002,NaN,1414800000,99.960,CO,80521
8,56d71d4205a4a48004000002,30500.0,1413158400,9.045,CO,80439
9,58fb33052c8739fff4000007,NaN,1413158400,150.000,CO,80401
10,577d1b462c8739e10800000b,100.0,1413158400,0.010,CO,80401
11,59b2af372c8739cb1200000a,21000.0,1413158400,10.000,CO,80401
12,5550e41005a4a4aca40000c1,21000.0,1412726400,13.550,CO,80831
13,54fd74ac27a49b361f808aca,141000.0,1403071200,45.000,CO,80127
14,54d6a56327a49b361f808aac,20000.0,1390892400,7.100,CO,80005
15,54809d3a27a49b361f808697,22000.0,1388559600,13.580,CO,80401
16,58c2ced42c8739375a000007,45000.0,1384473600,5.500,CO,80447
17,5434573d27a49b361f8084c6,NaN,1383285600,21.600,CO,80523
18,521603e327a49b3bdd0000c8,18000.0,1375336800,7.680,CO,81005
19,51cce63727a49b48290093ec,1000.0,1370152800,0.500,CO,80210
20,5195dea727a49b118700e517,27151.2,1365573600,6.480,CO,81520
21,5195dea727a49b118700e514,42345.6,1365141600,10.560,CO,81504
22,5195dea727a49b118700e513,43308.0,1364968800,10.800,CO,81521
23,5195dea727a49b118700e511,31173.6,1364796000,7.440,CO,81504
24,5195dea727a49b118700e512,25140.0,1364796000,6.000,CO,80017
25,5195dea727a49b118700e50e,55819.2,1364450400,13.920,CO,81507
26,5195dea727a49b118700e50f,16704.0,1364450400,3.840,CO,81507
27,536393b527a49b5ed1744b27,0.0,1364104800,3.430,CO,80130
28,5195dea727a49b118700e50b,22123.2,1363672800,5.280,CO,81504
29,5195dea727a49b118700e50a,47157.6,1363327200,11.760,CO,80007
...,...,...,...,...,...,...
2576,4c2a3c5b19cd1b5d3d01085e,NaN,1172732400,3.000,CO,80304
2577,4c2a3c6b19cd1b5d3d0112b4,NaN,1172732400,2.000,CO,80302
2578,4c2a3bfa19cd1b5d3d00c93a,74250.0,1171868400,9.900,CO,81501
2579,4c2a3b4f19cd1b5d3d005af6,74250.0,1170831600,9.900,CO,81501
2580,4c2a3acc19cd1b5d3d000c90,NaN,1170313200,5.160,CO,80305
2581,4c2a3ae419cd1b5d3d001b52,NaN,1170313200,3.000,CO,80304
2582,4c2a3af519cd1b5d3d00262d,NaN,1170313200,48.000,CO,80301
2583,4c2a3b6619cd1b5d3d006a7f,NaN,1170313200,10.300,CO,80301
2584,4c2a3b6919cd1b5d3d006c19,NaN,1170313200,4.000,CO,80304
2585,4c2a3b7a19cd1b5d3d00776d,NaN,1170313200,2.000,CO,80303
2586,4c2a3baf19cd1b5d3d0098ad,NaN,1170313200,3.200,CO,80304
2587,4c2a3c5319cd1b5d3d010360,NaN,1170313200,3.400,CO,80304
2588,4c2a3ada19cd1b5d3d0015ac,NaN,1167634800,6.000,CO,80304
2589,4c2a3b3f19cd1b5d3d0051ac,NaN,1167634800,3.400,CO,80305
2590,4c2a3bef19cd1b5d3d00c2c8,NaN,1167634800,2.800,CO,80302
2591,4c2a3c1d19cd1b5d3d00e04a,NaN,1167634800,11.000,CO,80304
2592,4c2a3c3e19cd1b5d3d00f5b6,NaN,1167634800,4.000,CO,80303
2593,4c2a3c5119cd1b5d3d010237,NaN,1167634800,2.000,CO,80301
2594,4c2a3c5519cd1b5d3d0104be,NaN,1167634800,4.000,CO,80304
2595,4c2a500919cd1b61bb000297,NaN,1167634800,10.000,CO,80304
2596,4c2a500919cd1b61bb0002a1,NaN,1167634800,3.000,CO,80304
2597,4c2a3bad19cd1b5d3d009761,30000.0,1157083200,3.400,CO,80121
2598,4c2a3bda19cd1b5d3d00b501,23700.0,1150956000,2.970,CO,80014
2599,4f0ce971455385339d000033,53000.0,1129183200,10.000,CO,80401
2600,4c2a3ad219cd1b5d3d001050,25000.0,933480000,1.600,CO,80538
2601,4c938eb1455385169d000003,6000.0,876722400,2.450,CO,80401
2602,4eaeef344553853a700000db,48000.0,876722400,10.000,CO,81652
2603,4f3551554553856f8c000157,21000.0,876722400,9.900,CO,80401
2604,525a38e927a49b0b81000029,2000.0,876722400,1.000,CO,80401
2605,535cf59527a49b7a2f084b8a,22000.0,876722400,3.010,CO,80401

In [51]:
file_name = "../data/colorado_installs.csv"
install_df.to_csv(file_name, sep='\t')

In [61]:
tsb = install_df.iloc[0]["date_installed"]
tsf = install_df.iloc[2605]["date_installed"]

print(datetime.utcfromtimestamp(tsb))
print(datetime.utcfromtimestamp(tsf))

2016-04-10 00:00:00
1997-10-13 06:00:00